### PR TITLE
Prepare Azure CI pipeline for OAuth

### PR DESCRIPTION
**Pull request by scholzj**
This PR adds the initial Azure CI pipeline to build and deploy the Oauth library. It currently runs only the unit tests but not the dedicated test suites. Therefore it does not remove x64 from the Travis pipeline. But it moves the deployment (pushing to Sonatype) to Azure and removes it from Travis.

### CODE REVIEW

**Review by im-konge — APPROVED** [review]

**Review by mstruk — APPROVED** [review]
I suppose GitHub integration to see Azure build results is still needed.

**Comment by scholzj** [comment]
> I suppose GitHub integration to see Azure build results is still needed.

@mstruk WDYM? The results can be seen in the status section next to the Travis results.

**Comment by mstruk** [comment]
> > I suppose GitHub integration to see Azure build results is still needed.
> 
> @mstruk WDYM? The results can be seen in the status section next to the Travis results.

Interesting. I don't see any badges for Azure at the bottom of this page, but if I click on Travis CI `Details` I now noticed that there is `Azure Pipelines` item there. Great, thanks.

**Comment by scholzj** [comment]
Strange. I have them there. Let's merge it and see if you have them on the future PRs or not.

**Pull request merged**
