### PR TITLE
Fixes #94

### LINKED ISSUE #94: Enable strimzi-kafka-oauth on ppc64le arch
Hey!

Thanks for the awesome readme/tutorials on strimzi-kafka-oauth. I could build strimzi-kafka-oauth from source & run the tests outlined, I was wondering what it would take to have the strimzi-kafka-oauth running on ppc64le. FWIW we have ppc64le instances in Travis.

### PR DESCRIPTION
**Pull request by krishvoor**
Add ppc64le support for Travis CI

Signed-off-by: Krishna Harsha Voora <krishvoor@in.ibm.com>

### CODE REVIEW

**Comment by krishvoor** [comment]
This support is to ensure the strimzi-kafka-oauth builds on ppc64le, also any further enhancements do not break it on ppc64le. Currently only enabled for ppc64le with OpenJDK11.

**Comment by krishvoor** [comment]
@scholzj - the error encountered is one-off and doesn't pertain to the patch submitted, request for restart.

**Comment by scholzj** [comment]
I do not see any errors anymore. However, this PR does only build and nothing else. It doesn't run any tests or anything. So it does not guarantee that things will work or that they will not break.

**Comment by krishvoor** [comment]
Thanks for the rebuild/restart, agreed, for JDK11 no test-cases are executed in particular for any.
I am actively working with hydra/keycloak & strimzi-kafka-operator communities to publish ppc64le architecture specific docker images, once published will enable ppc64le for JDK8 specific tests.

**Comment by scholzj** [comment]
For AMD64 they are executed on Java 8. But you did not add Java 8 for PPC64LE - so you should run the tests on Java 11 then.

**Comment by krishvoor** [comment]
Hey @scholzj  I am working with keycloak & hydra communities to get the docker images published for ppc64le. And it will be a while before I have the docker images in place. This change is only building it on ppc64le/s390x via the travis CI/CD, and would unconver any build failures currently for ppc64le as well, this shouldn't cause any issues, as we are not publishing any architecture specific artefacts.

Would you kindly review the PR perhaps ?

**Comment by scholzj** [comment]
Well, I think the s390x build is not always without issues. And I think never fails because the Java code but it is not unusual that it just randomly doesn't work. I think the experience on HTTP Bridge is similar. So for me personally, it is:
* Not clear about the added value when all it does is the build
* Without any knowledge about the platform and any environments to test / develop on, what are we expected to do when it stops working? Just remove it again?

So as I said before, I think this needs to have a bigger discussion about what the overall plan is, what your commitments are in terms of long term support etc. As suggested in the past, coming to the [Strimzi Community meetings](https://github.com/strimzi/strimzi-kafka-operator#strimzi-community-meetings) to discuss this would be great.

@strimzi/maintainers and @mstruk: If any of you have different feelings about it, feel free to review and merge it.

**Comment by krishvoor** [comment]
Hey @scholzj - Thanks for a very quick response.

As suggested earlier, we definitely stand-by our long-term commitment and ensure availability of servers for testing/developing of any new enhancements in case of any unlikely build/test failure. I am trying to get the mentioned resources ASAP. Only to get a headstart I requested this PR to be reviewed/merged early.

I hear the questions put forward and I plan to join the community meetings at the earliest i.e. the one scheduled towards end of March.

**Pull request closed without merging**
