### PR TITLE
Add s390x support for Travis CI

### PR DESCRIPTION
**Pull request by cnnaik**
Add s390x support for Travis CI

### CODE REVIEW

**Comment by scholzj** [comment]
A stupid question ... but what is the expected value? Are there some major differences with Java on s390x? How does this impact the tests which seems to be mostly using container images not necessarily built for s390x?

**Comment by cnnaik** [comment]
We have added this support to make sure that strimzi-kafka-oauth builds fine on s390x, also any further enhancements do not break it on s390x.

Also note that the changes are added only for OpenJDK11 on s390x which does not run any test cases.

**Comment by scholzj** [comment]
@cnnaik Actually, I thought this is running for both Java 8 and 11. But now I see that it runs Java 11 for S390x but one another build for Java 8 on amd64 (see here: https://travis-ci.org/strimzi/strimzi-kafka-oauth/builds/618455629). Is there some way to avoid that and run the Java 8 build only once?

**Comment by cnnaik** [comment]
@scholzj As per the build configuration of the jobs only 3 jobs should run for the changes made to the `travis.yml`. We tried to build in org environment (https://travis-ci.org/cnnaik/strimzi-kafka-oauth/builds/620092310) , we got 3 builds only in `strimzi-s390x-travis` branch. 

Could you please check if you can re-trigger the build?

**Comment by scholzj** [comment]
@cnnaik That is weird. Maybe it is related to how the merging of the PR works on Travis or something. Can you fix the DCO and I will try to merge and see what it does as a branch build.

**Comment by cnnaik** [comment]
@scholzj Fixed the DCO check. Please check.

**Comment by scholzj** [comment]
Hmm, seems to still do 4 branches on Strimzi Travis. It is strange that it behaves differently for your branch.

**Comment by scholzj** [comment]
@cnnaik For some reason it seems to work differently. As if you are on a different Travis version (did you maybe enabled the beta version?). But I got it fixed somehow - see #23.

**Comment by cnnaik** [comment]
@scholzj  No i have not enabled anything. 
Will this build create s390x specific jar files which will be available for download for the users?

**Comment by scholzj** [comment]
Do we need it? I don't think the jars contain any native code. So I think
it should not be needed.

**Pull request merged**
