### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by craicoverflow**
The file name is not the same as the actual file.

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
The change looks good to me. But can you fix the DCO signoff? We cannot merge it without it. The instructions should be under the _Details_ link next to DCO in the PR status area.

**Comment by craicoverflow** [comment]
Thanks, amended now with the DCO sign off.

**Review by mstruk — APPROVED** [review]
Yup, a typo. Good catch.

**Review by scholzj — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for the PR.

**Pull request merged**
