### PR TITLE
Testsuite with integration tests

### PR DESCRIPTION
**Pull request by mstruk**
This PR depends on https://github.com/strimzi/strimzi-kafka-oauth/pull/15

### CODE REVIEW

**Comment by scholzj** [comment]
I guess this contains the stuff from #15 as well? Should we wait untill #15 is merged than to not review it twice? Or are these other changes?

**Comment by mstruk** [comment]
@scholzj This should wait for #15 to be merged, then I'll rebase. I deliberately didn't add any reviewers :)

**Comment by scholzj** [comment]
@mstruk #15 is now merged. Could you please rebase this @mstruk so that we can review it and get it merged as well? Thanks.

**Comment by mstruk** [comment]
Branch is now rebased.

**Comment by mstruk** [comment]
Added testsuite run to TravisCI - only runs once - with Java 8.

**Pull request merged**
